/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.database_pro;

//import goods_customer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import location;

/**
 *
 * @author Dell
 */
public class Main_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Main_Screen
     */
    public Main_Screen() {
        initComponents();
       setLocationRelativeTo(null);

    }
/*public class home extends javax.swing.JPanel{
    public void paintCompnent(Graphic g){
    ImageIcon f=new ImageIcon("C:\\Users\\Google Tech\\Desktop");
    g.drawImage(f.getImage(),WIDTH,WIDTH,this );
    }*/


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        INFORMATION = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        USER = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PASSW = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane2.setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setLayout(null);

        INFORMATION.setBackground(new java.awt.Color(51, 51, 51));
        INFORMATION.setFont(new java.awt.Font("Kristen ITC", 1, 17)); // NOI18N
        INFORMATION.setForeground(new java.awt.Color(255, 255, 255));
        INFORMATION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-more-50.png"))); // NOI18N
        INFORMATION.setToolTipText("");
        INFORMATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFORMATIONActionPerformed(evt);
            }
        });
        jPanel1.add(INFORMATION);
        INFORMATION.setBounds(10, 670, 50, 20);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-location-25.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 600, 25, 25);

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-phone-32.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 630, 32, 32);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left.jpeg"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(0, 0, 420, 700);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right.jpeg"))); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(600, 0, 420, 700);

        jLabel2.setFont(new java.awt.Font("Stencil", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("30");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 400, 90, 50);

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("YEARS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(470, 480, 90, 80);

        jLabel26.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("OF");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(490, 560, 60, 60);

        jLabel27.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("EXPERIENCE");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(440, 620, 220, 60);

        jLabel29.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 51));
        jLabel29.setText("P");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(490, 0, 43, 60);

        jLabel30.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("O");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(490, 300, 43, 60);

        jLabel34.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("D");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(490, 220, 43, 60);

        jLabel35.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("A");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(490, 140, 43, 60);

        jLabel36.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("R");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(490, 70, 43, 60);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BLACK.jpeg"))); // NOI18N
        jPanel1.add(jLabel28);
        jLabel28.setBounds(-7, -4, 1030, 700);

        jTabbedPane2.addTab("HOME WINDOW  ", jPanel1);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0,0,0,70));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel4.setText("      LOGIN");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(151, 70, 232, 48);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("USER NAME");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(150, 190, 90, 20);
        jPanel2.add(USER);
        USER.setBounds(139, 220, 228, 35);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 300, 90, 20);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(200, 460, 110, 30);

        PASSW.setText("jPasswordField1");
        jPanel2.add(PASSW);
        PASSW.setBounds(140, 340, 228, 34);
        PASSW.getAccessibleContext().setAccessibleName("");

        jPanel5.add(jPanel2);
        jPanel2.setBounds(70, 0, 550, 660);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOCK.png"))); // NOI18N
        jPanel5.add(jLabel7);
        jLabel7.setBounds(670, 0, 350, 660);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jLabel8);
        jLabel8.setBounds(87, -4, 940, 670);

        jTabbedPane2.addTab("ADMIN WINDOW ", jPanel5);

        jPanel6.setLayout(null);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("NEXT");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(920, 660, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_1 (1).jpg"))); // NOI18N
        jPanel6.add(jLabel1);
        jLabel1.setBounds(770, 20, 240, 630);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_3 (1).jpg"))); // NOI18N
        jPanel6.add(jLabel3);
        jLabel3.setBounds(10, 20, 220, 630);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_33.jpg"))); // NOI18N
        jPanel6.add(jLabel9);
        jLabel9.setBounds(380, 20, 260, 630);

        jLabel11.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("W");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(290, 20, 60, 90);

        jLabel12.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("A");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(690, 290, 60, 90);

        jLabel13.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("D");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(690, 410, 60, 90);

        jLabel14.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("O");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(690, 520, 60, 90);

        jLabel15.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("R");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(690, 170, 60, 90);

        jLabel17.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("M");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(290, 480, 60, 90);

        jLabel18.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("P");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(690, 60, 60, 90);

        jLabel19.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("L");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(290, 190, 60, 90);

        jLabel20.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setText("O");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(290, 390, 60, 90);

        jLabel21.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("E");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(290, 100, 60, 90);

        jLabel23.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("C");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(290, 290, 60, 90);

        jLabel24.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 102, 0));
        jLabel24.setText("E");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(290, 590, 60, 90);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.jpeg"))); // NOI18N
        jPanel6.add(jLabel16);
        jLabel16.setBounds(-10, 0, 1040, 700);

        jTabbedPane2.addTab("CUSTOMER WINDOW", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INFORMATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFORMATIONActionPerformed
       dispose();// to close the curent frame
                    INFORMATION_FRAME IF = new INFORMATION_FRAME();// next GUI....
                    IF.setVisible(true);
                    // TODO add your handling code here:
    }//GEN-LAST:event_INFORMATIONActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       dispose();// to close the curent frame
        goods_customer GC = new goods_customer();// next GUI....
        GC.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
         String password = "09$0049";
         String user_name ="ADMIN OF BRADO";
                if ( USER.getText().equals(user_name) && PASSW.getText().equals(password))
            {
             dispose();// to close the curent frame
            ADMIN_FRAME aa = new ADMIN_FRAME();// next GUI....
            aa.setVisible(true); 
            
            }
                else {
                    // Password is incorrect, show JOptionPane message
                    JOptionPane.showMessageDialog(null, "Incorrect Password. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                    PASSW.setText("");
                    USER.setText("");
                    
                }
            
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         dispose();// to close the curent frame
                    OURLOCATION  u = new OURLOCATION();// next GUI.... 
                    u.setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();// to close the curent frame
        Connect  con = new Connect();// next GUI.... 
         con.setVisible(true);  
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INFORMATION;
    private javax.swing.JPasswordField PASSW;
    private javax.swing.JTextField USER;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables

    static class home {

        public home() {
        }
    }
}